### ISSUE TITLE
Create root image error

### ISSUE THREAD

**Issue by camz2000** [bhuman/DeepFieldBoundary#1]
Hi! I'm Camila Álvarez from the University of la Sabana, and I'm working with my team in the image processing optimization of the robot NAO, and we find intersting your code. Therefore, with my team, we are trying to compile this repository, but in the part of the root image, appears an error which says the following message:  
![image](https://user-images.githubusercontent.com/111761871/195864612-35b96d8c-6f4a-47cf-aa08-afece78c8351.png)
It seems that isn't creating a directory that allows the compilation of the code. 
I will apreciate if you could guide us to solve this problem. 
Thank you so much.

**Comment by ahasselbring** [comment]
We will reply to the issue in the other repository (bhuman/BHumanCodeRelease#53)
